[package]
name = "reflection-doc"
version = "0.1.0"
edition = "2024"
authors = [
  "adz <x12@adz.garden>",
  "Julian Sparber <julian@sparber.net>"
]

[dependencies]
reflection-node = { path = "../reflection-node" }
anyhow = "1.0.94"
async-channel = "2.3.1"
glib = "0.20"
gio = "0.20"
loro = "1.5"
p2panda-core = { git = "https://github.com/p2panda/p2panda", rev = "5e3816cc63af30ea5a8f3745e73ada265e700cf9", default-features = false }
thiserror = "2.0.11"
tracing = "0.1"
